# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY README.md .
COPY env_example.txt .env
COPY src src

# Install dependencies and project
RUN pip install --no-cache-dir .

EXPOSE 8000

# Default command: integrated server (MCP + OAuth web server)
CMD ["outlook-mcp"]
